# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import vuelos_pb2 as vuelos__pb2


class AsigStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Asig_pistas = channel.unary_unary(
        '/vuelos.Asig/Asig_pistas',
        request_serializer=vuelos__pb2.Request.SerializeToString,
        response_deserializer=vuelos__pb2.Response.FromString,
        )
    self.Asig_salida = channel.unary_unary(
        '/vuelos.Asig/Asig_salida',
        request_serializer=vuelos__pb2.Request.SerializeToString,
        response_deserializer=vuelos__pb2.Response.FromString,
        )


class AsigServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Asig_pistas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Asig_salida(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AsigServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Asig_pistas': grpc.unary_unary_rpc_method_handler(
          servicer.Asig_pistas,
          request_deserializer=vuelos__pb2.Request.FromString,
          response_serializer=vuelos__pb2.Response.SerializeToString,
      ),
      'Asig_salida': grpc.unary_unary_rpc_method_handler(
          servicer.Asig_salida,
          request_deserializer=vuelos__pb2.Request.FromString,
          response_serializer=vuelos__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'vuelos.Asig', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
