# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vuelos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vuelos.proto',
  package='vuelos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cvuelos.proto\x12\x06vuelos\",\n\x07Request\x12\x11\n\tip_client\x18\x01 \x01(\t\x12\x0e\n\x06\x61ltura\x18\x02 \x01(\x05\"^\n\x08Response\x12\x0f\n\x07permiso\x18\x01 \x01(\x08\x12\x10\n\x08pista_at\x18\x02 \x01(\x05\x12\x0e\n\x06\x61ltura\x18\x03 \x01(\x05\x12\x11\n\tip_server\x18\x04 \x01(\t\x12\x0c\n\x04\x61\x65ro\x18\x05 \x01(\t2j\n\x04\x41sig\x12\x30\n\x0b\x41sig_pistas\x12\x0f.vuelos.Request\x1a\x10.vuelos.Response\x12\x30\n\x0b\x41sig_salida\x12\x0f.vuelos.Request\x1a\x10.vuelos.Responseb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='vuelos.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_client', full_name='vuelos.Request.ip_client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altura', full_name='vuelos.Request.altura', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='vuelos.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='permiso', full_name='vuelos.Response.permiso', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pista_at', full_name='vuelos.Response.pista_at', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altura', full_name='vuelos.Response.altura', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_server', full_name='vuelos.Response.ip_server', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aero', full_name='vuelos.Response.aero', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'vuelos_pb2'
  # @@protoc_insertion_point(class_scope:vuelos.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'vuelos_pb2'
  # @@protoc_insertion_point(class_scope:vuelos.Response)
  ))
_sym_db.RegisterMessage(Response)



_ASIG = _descriptor.ServiceDescriptor(
  name='Asig',
  full_name='vuelos.Asig',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=166,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='Asig_pistas',
    full_name='vuelos.Asig.Asig_pistas',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Asig_salida',
    full_name='vuelos.Asig.Asig_salida',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASIG)

DESCRIPTOR.services_by_name['Asig'] = _ASIG

# @@protoc_insertion_point(module_scope)
